### ISSUE TITLE
Control doesn't update on queries page

### ISSUE THREAD

**Issue by davidcorrigan714** [microsoft/vsts-extension-integer-control#13]
So this control doesn't update when it's shown on the side pane of query results and you click through the query results.

I personally think it's a fundamental issue with the queries page, but DevOps Support disagrees. See here:
https://developercommunity.visualstudio.com/content/problem/629249/custom-controls-dont-update-on-side-pane-in-querie.html

**Comment by obvioussean** [comment]
Fixed with #14
